create type tipo_usuario_enum as enum ('PESSOA_FISICA', 'EMPRESA', 'ADMIN');

alter type tipo_usuario_enum owner to postgres;

create type tipo_transacao_enum as enum ('GANHO_CODIGO', 'GASTO_VOUCHER', 'GANHO_CAMPANHA');

alter type tipo_transacao_enum owner to postgres;

create table enderecos
(
    id          integer generated by default as identity
        primary key,
    cep         varchar(9)   not null,
    logradouro  varchar(255) not null,
    numero      varchar(20),
    complemento varchar(100),
    bairro      varchar(100) not null,
    cidade      varchar(100) not null,
    estado      char(2)      not null
        constraint chk_estado_len
            check (char_length(estado) = 2),
    latitude    numeric(10, 8),
    longitude   numeric(11, 8)
);

alter table enderecos
    owner to postgres;

create index idx_enderecos_cidade_estado
    on enderecos (cidade, estado);

create table usuarios
(
    id            integer generated by default as identity
        primary key,
    nome          varchar(255)      not null,
    email         varchar(255)      not null
        unique,
    senha_hash    varchar(255)      not null,
    telefone      varchar(20),
    tipo_usuario  tipo_usuario_enum not null,
    cpf           varchar(14)
        unique,
    data_cadastro timestamp with time zone default CURRENT_TIMESTAMP,
    ativo         boolean                  default true
);

alter table usuarios
    owner to postgres;

create table usuario_enderecos
(
    usuario_id       integer not null
        references usuarios
            on delete cascade,
    endereco_id      integer not null
        references enderecos
            on delete cascade,
    is_principal     boolean default false,
    apelido_endereco varchar(50),
    primary key (usuario_id, endereco_id)
);

alter table usuario_enderecos
    owner to postgres;

create table empresas
(
    id                  integer generated by default as identity
        primary key,
    usuario_id          integer      not null
        unique
        references usuarios
            on delete restrict,
    razao_social        varchar(255) not null,
    nome_fantasia       varchar(255),
    cnpj                varchar(18)  not null
        unique,
    endereco_id         integer
                                     references enderecos
                                         on delete set null,
    aprovada_pelo_admin boolean default false
);

alter table empresas
    owner to postgres;

create index idx_empresas_aprovada
    on empresas (aprovada_pelo_admin);

create table pontos_coleta
(
    id                    integer generated by default as identity
        primary key,
    empresa_id            integer      not null
        references empresas
            on delete cascade,
    endereco_id           integer      not null
        unique
        references enderecos
            on delete restrict,
    nome_ponto            varchar(255) not null,
    horario_funcionamento text,
    ativo                 boolean default true
);

alter table pontos_coleta
    owner to postgres;

create table tipos_residuos
(
    id        integer generated by default as identity
        primary key,
    nome      varchar(100) not null
        unique,
    descricao text
);

alter table tipos_residuos
    owner to postgres;

create table empresa_aceita_residuo
(
    empresa_id      integer not null
        references empresas
            on delete cascade,
    tipo_residuo_id integer not null
        references tipos_residuos
            on delete cascade,
    primary key (empresa_id, tipo_residuo_id)
);

alter table empresa_aceita_residuo
    owner to postgres;

create table pontocoleta_aceita_residuo
(
    ponto_coleta_id integer not null
        references pontos_coleta
            on delete cascade,
    tipo_residuo_id integer not null
        references tipos_residuos
            on delete cascade,
    primary key (ponto_coleta_id, tipo_residuo_id)
);

alter table pontocoleta_aceita_residuo
    owner to postgres;

create table agendamentos_coleta
(
    id                     integer generated by default as identity
        primary key,
    usuario_id             integer                                                          not null
        references usuarios
            on delete cascade,
    empresa_id             integer                                                          not null
        references empresas
            on delete cascade,
    endereco_coleta_id     integer                                                          not null
        references enderecos
            on delete restrict,
    data_solicitacao       timestamp with time zone default CURRENT_TIMESTAMP,
    data_agendada          timestamp with time zone,
    status                 varchar(50)              default 'SOLICITADO'::character varying not null,
    volume_estimado_m3     numeric(10, 2),
    peso_estimado_kg       numeric(10, 2),
    observacoes_usuario    text,
    justificativa_rejeicao text
);

alter table agendamentos_coleta
    owner to postgres;

create index idx_agendamentos_status
    on agendamentos_coleta (status);

create table itens_agendamento
(
    id              integer generated by default as identity
        primary key,
    agendamento_id  integer           not null
        references agendamentos_coleta
            on delete cascade,
    tipo_residuo_id integer           not null
        references tipos_residuos
            on delete restrict,
    quantidade      integer default 1 not null
);

alter table itens_agendamento
    owner to postgres;

create table codigos_diarios_ponto_coleta
(
    id              integer generated by default as identity
        primary key,
    ponto_coleta_id integer     not null
        references pontos_coleta
            on delete cascade,
    codigo          varchar(20) not null,
    data_validade   date        not null,
    pontos_valor    integer     not null,
    unique (ponto_coleta_id, data_validade),
    unique (codigo, data_validade)
);

alter table codigos_diarios_ponto_coleta
    owner to postgres;

create index idx_codigos_diarios_data
    on codigos_diarios_ponto_coleta (data_validade);

create table resgates_usuario
(
    id               integer generated by default as identity
        primary key,
    usuario_id       integer not null
        references usuarios
            on delete cascade,
    codigo_diario_id integer not null
        references codigos_diarios_ponto_coleta
            on delete cascade,
    data_resgate     timestamp with time zone default CURRENT_TIMESTAMP,
    unique (usuario_id, codigo_diario_id)
);

alter table resgates_usuario
    owner to postgres;

create table vouchers
(
    id                       integer generated by default as identity
        primary key,
    nome_parceiro            varchar(255) not null,
    titulo                   varchar(255) not null,
    descricao                text,
    custo_pontos             integer      not null,
    validade                 date,
    quantidade_disponivel    integer,
    cadastrado_pelo_admin_id integer
                                          references usuarios
                                              on delete set null
);

alter table vouchers
    owner to postgres;

create table usuario_vouchers
(
    id                    integer generated by default as identity
        primary key,
    usuario_id            integer      not null
        references usuarios
            on delete cascade,
    voucher_id            integer      not null
        references vouchers
            on delete restrict,
    data_resgate          timestamp with time zone default CURRENT_TIMESTAMP,
    pontos_gastos         integer      not null,
    codigo_voucher_gerado varchar(100) not null
        unique,
    utilizado             boolean                  default false
);

alter table usuario_vouchers
    owner to postgres;

create index idx_usuario_vouchers_usuario_id
    on usuario_vouchers (usuario_id);

create table transacoes_pontos
(
    id             integer generated by default as identity
        primary key,
    usuario_id     integer             not null
        references usuarios
            on delete cascade,
    tipo_transacao tipo_transacao_enum not null,
    pontos         integer             not null,
    data_transacao timestamp with time zone default CURRENT_TIMESTAMP,
    descricao      varchar(255),
    referencia_id  integer
);

alter table transacoes_pontos
    owner to postgres;

create index idx_transacoes_usuario_data
    on transacoes_pontos (usuario_id, data_transacao);

create table artigos
(
    id              integer generated by default as identity
        primary key,
    titulo          varchar(255) not null,
    conteudo        text         not null,
    autor_id        integer
                                 references usuarios
                                     on delete set null,
    data_publicacao timestamp with time zone default CURRENT_TIMESTAMP,
    publicado       boolean                  default true
);

alter table artigos
    owner to postgres;

create table campanhas
(
    id                integer generated by default as identity
        primary key,
    titulo            varchar(255)      not null,
    descricao         text,
    data_inicio       date              not null,
    data_fim          date              not null,
    ativa             boolean default true,
    pontos_por_adesao integer default 0 not null
);

alter table campanhas
    owner to postgres;

create table campanha_empresa
(
    campanha_id integer not null
        references campanhas
            on delete cascade,
    empresa_id  integer not null
        references empresas
            on delete cascade,
    primary key (campanha_id, empresa_id)
);

alter table campanha_empresa
    owner to postgres;

create table campanha_ponto_coleta
(
    campanha_id     integer not null
        references campanhas
            on delete cascade,
    ponto_coleta_id integer not null
        references pontos_coleta
            on delete cascade,
    primary key (campanha_id, ponto_coleta_id)
);

alter table campanha_ponto_coleta
    owner to postgres;

create table usuario_campanha
(
    usuario_id  integer not null
        references usuarios
            on delete cascade,
    campanha_id integer not null
        references campanhas
            on delete cascade,
    data_adesao timestamp with time zone default CURRENT_TIMESTAMP,
    ativo       boolean                  default true,
    primary key (usuario_id, campanha_id)
);

alter table usuario_campanha
    owner to postgres;

